#!/bin/bash
# RENDER DEPLOYMENT FIX - Backend Build Configuration

echo "🔧 RegGuard Backend Deployment Configuration"
echo "=============================================="
echo ""
echo "✅ Step 1: Verify Build Environment"
echo ""
echo "Your Render backend build needs these exact commands:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "BUILD COMMAND:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "pip install --no-cache-dir -r backend/requirements.txt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "START COMMAND:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd backend && python -m uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Step 2: Required Environment Variables in Render"
echo ""
echo "Required API Keys (all must be set):"
echo "  • GOOGLE_MAPS_API_KEY (rotated - new key)"
echo "  • GEMINI_API_KEY (rotated - new key)"
echo "  • STRIPE_SECRET_KEY (rotated - new key)"
echo "  • STRIPE_WEBHOOK_SECRET (rotated - new key)"
echo "  • SUPABASE_KEY (sb_service_role_... - service role key)"
echo "  • RESEND_FROM_EMAIL=noreply@regguardagent.com"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Step 3: Render Configuration Checklist"
echo ""
echo "☐ Go to: https://dashboard.render.com/"
echo "☐ Select service: regguard-api"
echo "☐ Go to: Settings"
echo "☐ Update Build Command (copy exactly):"
echo "  pip install --no-cache-dir -r backend/requirements.txt"
echo ""
echo "☐ Update Start Command (copy exactly):"
echo "  cd backend && python -m uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "☐ Go to: Environment"
echo "☐ Verify ALL these keys are present and NOT empty:"
echo "  - GOOGLE_MAPS_API_KEY (new rotated key)"
echo "  - GEMINI_API_KEY (new rotated key)"
echo "  - STRIPE_SECRET_KEY (new rotated key)"
echo "  - STRIPE_WEBHOOK_SECRET (new rotated key)"
echo "  - SUPABASE_KEY (service role key, starts with sb_service_role_)"
echo "  - RESEND_FROM_EMAIL"
echo ""
echo "☐ Click: Save"
echo "☐ Wait for auto-redeploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Step 4: Vercel Configuration Checklist"
echo ""
echo "☐ Go to: https://vercel.com/"
echo "☐ Select project: regguard-live"
echo "☐ Settings → Environment Variables"
echo "☐ Verify these VITE_ prefixed variables exist:"
echo "  - VITE_STRIPE_PUBLIC_KEY (pk_live_...)"
echo "  - VITE_SUPABASE_ANON_KEY (sb_anon_... or sb_publishable_...)"
echo "  - VITE_GOOGLE_MAPS_API_KEY (AIzaSy...)"
echo "  - VITE_BACKEND_ORIGIN (https://regguard-api.onrender.com)"
echo ""
echo "☐ Click: Redeploy"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Summary: What to Check"
echo ""
echo "After deployment, verify:"
echo "  1. Render backend health: curl https://regguard-api.onrender.com/health"
echo "  2. Vercel frontend: https://regguard-live.vercel.app"
echo "  3. Free trial form works: Try submitting a test"
echo "  4. No errors in console or logs"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
