#!/bin/bash
# 🚀 AUTOMATED RENDER DEPLOYMENT FIX SCRIPT
# Run this manually by copying/pasting the commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        RENDER BACKEND DEPLOYMENT FIX - MANUAL SETUP            ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "⚠️  You must do these steps in the Render Dashboard yourself:"
echo ""
echo "1. Go to: https://dashboard.render.com/"
echo "2. Click: regguard-api service"
echo "3. Click: Settings tab"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Build Command"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Find the 'Build Command' field"
echo "Clear it completely"
echo "Copy and paste THIS EXACTLY:"
echo ""
echo "  pip install -r backend/requirements.txt"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Start Command"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Find the 'Start Command' field"
echo "Clear it completely"
echo "Copy and paste THIS EXACTLY:"
echo ""
echo "  cd backend && uvicorn main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Click: Environment tab"
echo "Scroll through and verify EVERY one of these has a value:"
echo ""
echo "  ☐ GOOGLE_MAPS_API_KEY (should be: AIzaSy...)"
echo "  ☐ GEMINI_API_KEY (should be: new rotated key)"
echo "  ☐ STRIPE_SECRET_KEY (should be: sk_live_...)"
echo "  ☐ STRIPE_WEBHOOK_SECRET (should be: whsec_...)"
echo "  ☐ SUPABASE_KEY (should be: sb_service_role_...)"
echo "  ☐ SUPABASE_URL (should be: https://cukshjdvlydzxiqnjdaw.supabase.co)"
echo "  ☐ RESEND_FROM_EMAIL (should be: noreply@regguardagent.com)"
echo ""
echo "If any are EMPTY: Click it, paste the value, click Save"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Deploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Click: Save button (if you haven't already)"
echo "Go to: Deployments tab"
echo "Click: Redeploy button"
echo "Wait: 3-5 minutes for build to complete"
echo ""
echo "✅ When it shows 'Ready' (green) = Success!"
echo ""
