#!/bin/bash
# 🚀 AUTOMATED VERCEL DEPLOYMENT FIX SCRIPT
# Run this manually by copying/pasting the commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║        VERCEL FRONTEND DEPLOYMENT FIX - MANUAL SETUP           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "⚠️  You must do these steps in the Vercel Dashboard yourself:"
echo ""
echo "1. Go to: https://vercel.com/"
echo "2. Click: regguard-live project"
echo "3. Click: Settings tab"
echo "4. Click: Build and Deployment section"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: Root Directory"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Find the 'Root Directory' field"
echo "Click it"
echo "Delete any value in it"
echo "Leave it EMPTY"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Build Command"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Find the 'Build Command' field"
echo "Click it"
echo "Delete any value in it"
echo "Leave it EMPTY"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Output Directory"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Find the 'Output Directory' field"
echo "Click it"
echo "Delete any value in it"
echo "Leave it EMPTY"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Environment Variables (Optional Check)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Click: Environments tab (left sidebar)"
echo "Verify these VITE_ prefixed variables exist with values:"
echo ""
echo "  ☐ VITE_STRIPE_PUBLIC_KEY (should be: pk_live_...)"
echo "  ☐ VITE_SUPABASE_ANON_KEY (should be: sb_anon_... or sb_publishable_...)"
echo "  ☐ VITE_GOOGLE_MAPS_API_KEY (should be: AIzaSy...)"
echo "  ☐ VITE_BACKEND_ORIGIN (should be: https://regguard-api.onrender.com)"
echo ""
echo "If any are missing: Click 'Add Environment Variable' and add them"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Deploy"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go back to: Build and Deployment tab"
echo "Click: Save button"
echo "Go to: Deployments tab"
echo "Click: Redeploy button"
echo "Wait: 3-5 minutes for build to complete"
echo ""
echo "✅ When it shows 'Ready' (green) = Success!"
echo ""
